Repository metal3-io/utility-images, pull requests merged in 2025-03, with the labels that each got.

#29 :book: move mboukhalfa to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved

#30 :seedling: add dependabot config for github actions
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#28 :seedling: add basic pr workflows
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: lgtm, size/M, approved

#31 :seedling: group all github action bumps into single PR
  .github/dependabot.yml
Labels: lgtm, size/XS, approved

#27 :sparkles: move keepalived here from BMO repo
  keepalived/Dockerfile
  keepalived/configure-nonroot.sh
  keepalived/manage-keepalived.sh
  keepalived/sample.keepalived.conf
Labels: lgtm, size/M, approved

#33 :sparkles: add keepalived image build workflow
  .github/workflows/build-images-action.yml
Labels: size/S, lgtm, approved
